parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
settings:
  react:
    pragma:
    version: detect
rules:
  '@next/next/no-head-element': off
