name: CI

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  macos:
    needs: lint
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30

    steps:
      - run: uname -a
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
      - name: Cache Desktop node_modules
        id: cache-desktop-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install Desktop node_modules
        if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NPM_CONFIG_LOGLEVEL: verbose
      - run: npm run package:build
