name: CI

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      APPLE_API_KEY: ./certs/apple-api-key.p8
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
    steps:
      - run: uname -a
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
      - name: Cache Desktop node_modules
        id: cache-desktop-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install Desktop node_modules
        if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NPM_CONFIG_LOGLEVEL: verbose
      - name: Write Apple Developer credentials to file
        run: echo ${{ secrets.APPLE_API_KEY }} > ./certs/apple-api-key.p8
      - run: npm run package:build
