name: Common CI

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx format:check --all
      - run: git branch --track main origin/main
      - run: npx nx affected -t check
