name: Desktop CI

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

jobs:
  desktop-macos:
    name: Build macOS
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - run: uname -a
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npx nx run desktop:check
      - run: npx nx run desktop:build
